[package]
name = "mpw-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

mpw = { path="../mpw" }

clap = "2"
colored = "2"
env_logger = "0.7.0"
rpassword = "4"
